[package]
name = "paramacode/prefabcache"
version = "1.0.0"
description = "A typed and configurable pooling system for Roblox instances that efficiently manages prefab cloning, reuse, and lifecycle with automatic expansion."
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = [
  "src/**",
  "out/**",
  "LICENSE.txt",
  "README.md",
  "wally.toml"
]

exclude = [
  "node_modules/**",
  ".vscode/**",
  "docs/**",
  "*.toml",
  "*.json",
  "*.tgz"
]

[dependencies]
